name: pagify
description: "A flexible and customizable Flutter package for handling paginated data with minimal setup."
version: 0.2.8
homepage: https://github.com/ahmedemara231/pagination_helper

topics:
  - pagination
  - lazyloading
  - wifi
  - network
  - api

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.1.0
  dio: ^5.9.0
  http: ^1.6.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
#flutter:
#  assets:
#    - assets/lottie/
